### ISSUE TITLE
Possible error if counter_aggregate stops between it's Pid lookup and a message is sent to it

### ISSUE THREAD

**Issue by luisgerhorst** [bryanhunter/cqrs-with-erlang#1]
Hi,
I have a system with a very similar pattern where a process which's Pid can be looked up using a ID stops after a specific timeout if it doesn't receive any messages. I thought it would be a problem if someone looks up the Pid and then sends a message to it but the process with the Pid decides to terminate in the meantime so I tried to prevent it from happening with some manager process which turned out to be very complicated. What do you think about this? Is it valid to just assume it doesn't happen and let a caller crash from time to time?

**Comment by bryanhunter** [comment]
Yes, that's one of the (many) places where this sample cuts corners. if you’re doing this for real, using a gen_server for bank_account.erl would be a much better way to proceed. In the sample for the demo, I felt I should show the internals of what happens in an Erlang server process rather than use gen_server which hides the guts. The flip-side is: for conciseness I had to leave out a lot of the grown-up things that a gen_server does. Also, if I had used a gen_server, I would have modeled the API functions with calls instead of casts.

As you note the async calls in the sample don't give the bank_command_handler any useful feedback. If the Pid has died (timed out) and you send it a deposit (`Pid ! {attempt_command, {deposit_money, Amount}}.`) the money is thrown into the void. Really, really bad! Haha!

A simple way to patch this bug without changing much else would be to send _any_ message to the Pid before asking if it is alive (`is_process_alive(Pid)`) . Perhaps something like `Pid ! nudge` at `/keypid.erl#L24` This is a bit corny and means our keypid knows more about the intimate timeout internals of our `bank_account` than it probably should. 

Really happy you found this and have been kicking the tires. When I get a chance I’ll add a branch named “less dreadful” that has a cleaner implementation which isn’t as focussed on the quick demo.

**Comment by luisgerhorst** [comment]
Ok! Thanks for the answer I was just wondering if it's _the erlang way_ of doing stuff. I think I'll just try making everything where something like this could happen rely on calls instead of casts or maybe use `is_process_alive` (didn't know about this, thanks!).
